
// :::::::::::::::::::::::::::::::::::::::::::::::		TEMPERATURA		 :::::::::::::::::::::::::::::::::::::::::::::::
###

POST https://apirestp2ace2.herokuapp.com/temperatura HTTP/1.1
content-type: application/json


{
	"temperatura": 22
}

###

GET https://apirestp2ace2.herokuapp.com/temperatura HTTP/1.1
content-type: application/json

// :::::::::::::::::::::::::::::::::::::::::::::::		TIEMPO		 :::::::::::::::::::::::::::::::::::::::::::::::
###

POST https://apirestp2ace2.herokuapp.com/dato HTTP/1.1
content-type: application/json


{
	"id": "98",
    "tiempo": 22
}

###

GET https://apirestp2ace2.herokuapp.com/dato?fecha=11/14/2020 HTTP/1.1
content-type: application/json
